# example config for a python project
default_stages: [commit]
repos:
  - repo: ~/repos/dotrc
    rev: master
    hooks:
      - id: do-not-commit
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings, flake8-bugbear]
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3
