#! /bin/bash

home_to_here=$(realpath $(dirname $BASH_SOURCE) --relative-to ~)

# bash
if [[ $OSTYPE == linux-gnu* ]]; then  # WSL, GNU
  ln -s ~/$home_to_here/bashrc ~/.bashrc
  ln -s ~/$home_to_here/dir_colors ~/.dir_colors
elif [[ $OSTYPE == darwin* ]]; then  # macOS
  ln -s ~/$home_to_here/bashrc ~/.bash_profile
fi
ln -s ~/$home_to_here/inputrc ~/.inputrc

# vim
ln -sT ~/$home_to_here/vim   ~/.vim
ln -s ~/$home_to_here/vim/vimrc ~/.vimrc

# emacs
ln -sT ~/$home_to_here/emacs.d ~/.emacs.d

# git
ln -sT ~/$home_to_here/git ~/.git
ln -s ~/$home_to_here/git/gitconfig ~/.gitconfig
ln -s ~/$home_to_here/git/hooks/pre-commit git/templateDir/hooks/pre-commit
ln -s ~/$home_to_here/git/hooks/pre-push git/templateDir/hooks/pre-push

# python
ln -s ~/$home_to_here/python/flake8 ~/.config/flake8
