#! /bin/bash

home_to_here=$(realpath $(dirname $BASH_SOURCE) --relative-to ~)
ln -s $home_to_here/.bashrc ~/.bashrc
if [[ $OSTYPE == linux-gnu* ]]; then # WSL, GNU
  ln -s $home_to_here/.dir_colors ~/.dir_colors
fi
